modLoader="javafml"
loaderVersion="[51,)"
license="MIT"

[[mods]]
modId="tu_mod"
version="1.0.0"
displayName="Mi Primer Mod"
description='''Este es mi primer mod usando Forge 1.21'''

# Optional information
authors="Erkoke108"
credits="Gracias a Forge y Minecraft por hacerlo posible"
url="https://github.com/Erkoke108/MinecraftMod"
